Repository palantir/gradle-baseline, pull requests merged in 2019-06, with the labels that each got.

#649 [improvement] New PreferBuiltInConcurrentKeySet suggestion
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySet.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySetTests.java
Labels: merge when ready

#613 Publish plugin to gradle portal
  baseline-error-prone/build.gradle
  build.gradle
  gradle-baseline-java-config/build.gradle
  gradle-baseline-java/build.gradle
  gradle-junit-reports/build.gradle
  gradle/bintray-publish.gradle
  gradle/java.gradle
  gradle/publish-jar.gradle
Labels: merge when ready

#652 [improvement] Sensible defaults for test tasks (HeapDumpOnOutOfMemory)
  README.md
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: merge when ready

#659 Revert "[improvement] Ensure Optional#orElse argument is not method invocation"
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocation.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
Labels: autorelease

#660 [improvement] Support auto-applying error-prone suggested fixes
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: autorelease, merge when ready

#661 [improvement] Refaster rule compilation
  baseline-refaster-javac-plugin/build.gradle
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompiler.java
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompilerAnalyzer.java
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/CollectionsIsEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SortedFirst.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/Utf8Length.java
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/RefasterCompileTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneRefasterIntegrationTest.groovy
  settings.gradle
  versions.props
Labels: merge when ready

#666 [improvement] JUnit 5 boilerplate
  README.md
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-testing.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: merge when ready

#667 [fix] Fix refaster compilation to support version recommendations
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/RefasterCompileTask.java
Labels: merge when ready

#654 [improvement] Error-prone check to help prevent logging AuthHeader and BearerToken
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreventTokenLogging.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreventTokenLoggingTests.java
  versions.props
Labels: merge when ready

#669 [fix] fix potential NPE when configuring testing
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: autorelease, merge when ready
