Repository palantir/gradle-baseline, pull requests merged in 2019-07, with the labels that each got.

#673 Ignore DesignForExtension for ParameterizedTest
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready

#674 [fix] Prevent null from flagging as authentication information in PreventTokenLogging check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreventTokenLogging.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreventTokenLoggingTests.java
  changelog/@unreleased/pr-674.v2.yml
Labels: autorelease, merge when ready

#681 Support Java12 by suppressing one error-prone check
  changelog/@unreleased/pr-681.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#680 Revert "Revert "[improvement] Ensure Optional#orElse argument is not method invocation""
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocation.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
Labels: merge when ready, no changelog

#679 add refaster rule to migrate away from orElse(supplier.get())
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/OptionalOrElseSupplier.java
  changelog/@unreleased/pr-679.v2.yml
Labels: merge when ready

#688 Ensure format executes after compile
  changelog/@unreleased/pr-688.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
Labels: autorelease, merge when ready

#690 Autofix orElseGet
  changelog/@unreleased/pr-690.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: merge when ready

#687 Disallow dangling parenthesis
  changelog/@unreleased/pr-687.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
Labels: autorelease, merge when ready, spotless

#694 Don't cache test tasks
  changelog/@unreleased/pr-694.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: autorelease, merge when ready

#696 Don't cache when applying errorprone / refaster rules
  changelog/@unreleased/pr-696.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#697 Test helper for refaster checks
  .gitignore
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/CollectionsIsEmptyTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/OptionalOrElseSupplierTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SortedFirstTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/Utf8LengthTest.java
  baseline-refaster-testing/build.gradle
  baseline-refaster-testing/src/main/java/com/palantir/baseline/refaster/CompilerUtility.java
  baseline-refaster-testing/src/main/java/com/palantir/baseline/refaster/RefasterTestHelper.java
  changelog/@unreleased/pr-697.v2.yml
  settings.gradle
Labels: autorelease, merge when ready

#702 Separate positive test cases
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocation.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchBlockLogExceptionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GuavaPreconditionsConstantMessageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GuavaPreconditionsMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LogSafePreconditionsConstantMessageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LogSafePreconditionsMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
  changelog/@unreleased/pr-702.v2.yml
Labels: merge when ready

#701 Correctly configure Junit5 for non-default test sets
  changelog/@unreleased/pr-701.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: autorelease, merge when ready

#709 Allow method references in Optional orElse
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocation.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
  changelog/@unreleased/pr-709.v2.yml
Labels: autorelease, merge when ready

#712 Do not overwrite junit5 test config
  changelog/@unreleased/pr-712.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: autorelease, merge when ready

#714 add check to ensure junit5 tests are not used with junit4 Rule/ClassRule
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JUnit5RuleUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JUnit5RuleUsageTest.java
  changelog/@unreleased/pr-714.v2.yml
Labels: merge when ready

#707 Use Eclipse formatter (behind -Pcom.palantir.baseline-format.eclipse feature flag)
  README.md
  changelog/@unreleased/pr-707.v2.yml
  gradle-baseline-java-config/resources/spotless/eclipse.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineConfigIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatTest.groovy
Labels: autorelease, merge when ready

#715 Checkstyle now accepts the output of the eclipse formatter
  changelog/@unreleased/pr-715.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: autorelease, merge when ready
