Repository palantir/gradle-baseline, pull requests merged in 2019-12, with the labels that each got.

#1079 Error prone `AssertjPrimitiveComparison` for primitive comparisons
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AssertjPrimitiveComparison.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AssertjSingleAssertMatcher.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/AssertjPrimitiveComparisonTest.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanOrEqualTo.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanOrEqualToWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanOrEqualTo.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanOrEqualToWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjPrimitiveEquals.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjPrimitiveEqualsWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjInequalitiesTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjPrimitiveEqualsTest.java
  changelog/@unreleased/pr-1079.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1080 Fix readme spelling s/modifiations/modifications
  README.md
Labels: merge when ready, no changelog

#1083 Fix GradleCacheableTaskAction on error-prone 2.3.4
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GradleCacheableTaskAction.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jConstantLogMessageTests.java
Labels: no changelog

#1082 errorprone 2.3.3 -> 2.3.4
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GradleCacheableTaskAction.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReadReturnValueIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jConstantLogMessageTests.java
  build.gradle
  changelog/@unreleased/pr-1082.v2.yml
  versions.props
Labels: autorelease, merge when ready

#1084 Un-suppress check on this repo
  build.gradle
Labels: merge when ready, no changelog

#1085 Add dependency on mockito-errorprone
  baseline-error-prone/build.gradle
  changelog/@unreleased/pr-1085.v2.yml
  versions.props
Labels: autorelease, merge when ready

#1074 Error prone ExceptionSpecificity check to avoid catching too broadly
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreASTHelpers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowSpecificity.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchSpecificityTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ThrowSpecificityTest.java
  changelog/@unreleased/pr-1074.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1094 PreferJavaTimeOverload:OFF
  changelog/@unreleased/pr-1094.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1098 Disable ThrowSpecificty and CatchSpecificity fixes by default
  changelog/@unreleased/pr-1098.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1102 Don't apply errorprone rules to refaster rules project
  baseline-refaster-rules/build.gradle
Labels: merge when ready, no changelog

#1109 Allow non-default errorprone fixes to be applied from the command line
  README.md
  changelog/@unreleased/pr-1109.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: merge when ready

#1070 NonComparableStreamSort validates direct types
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/NonComparableStreamSort.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/NonComparableStreamSortTests.java
  changelog/@unreleased/pr-1070.v2.yml
Labels: merge when ready

#1110 Migrate baseline error-prone checks to use jdk13 compatible qualifiers
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AssertjPrimitiveComparison.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreASTHelpers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreSuggestedFixes.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySet.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionConstructors.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionTransform.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferListsPartition.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggingPreconditions.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReadReturnValueIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictCollectionIncompatibleType.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowError.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowSpecificity.java
  changelog/@unreleased/pr-1110.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1117 Decouple gradle-palantir-java-format code from baseline
  build.gradle
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/format/PalantirJavaFormatStep.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1118 Document ThrowSpecificity and CatchSpecificity edge cases
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowSpecificity.java
  changelog/@unreleased/pr-1118.v2.yml
Labels: merge when ready

#1123 Gauges should be registered with `registerWithReplacement`
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ExecutorSubmitRunnableFutureIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreSuggestedFixes.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReadReturnValueIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLevelCheck.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnsafeGaugeRegistration.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnsafeGaugeRegistrationTest.java
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/TritiumReplaceGauge.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/TritiumReplaceGaugeTest.java
  changelog/@unreleased/pr-1123.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  versions.lock
  versions.props
Labels: merge when ready

#1126 Use explicit CommandLineArgumentProviders instead of lambdas
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, no changelog

#1128 Remove AssertjPrimitiveComparison from default-patch-checks
  changelog/@unreleased/pr-1128.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1130 Implement BracesRequired error-prone check with suggested fixes
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/BracesRequired.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/BracesRequiredTest.java
  changelog/@unreleased/pr-1130.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1134 Mark test resources as test resources in IntelliJ
  changelog/@unreleased/pr-1134.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready
