Repository palantir/gradle-baseline, pull requests merged in 2019-10, with the labels that each got.

#917 Remove refaster AssertjIsOne, which isn't worthwhile
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjIsOne.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjIsOneTest.java
  changelog/@unreleased/pr-917.v2.yml
Labels: merge when ready

#919 Add assertj refaster rules for map size asserts
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapHasSizeExactly.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapHasSizeExactlyWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapIsEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapIsEmpty2.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapIsEmptyWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjMapHasSizeTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjMapIsEmptyTest.java
  changelog/@unreleased/pr-919.v2.yml
Labels: merge when ready

#918 extra AssertjOptionalHasValue case
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValue.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValueWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjOptionalHasValueTest.java
Labels: merge when ready, no changelog

#922 Implement AssertjCollectionHasSameSizeAsArray
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSameSizeAsArray.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjCollectionHasSameSizeAsTest.java
  changelog/@unreleased/pr-922.v2.yml
Labels: merge when ready

#925 Implement assertj map refactors for containsKey and containsEntry
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapContainsEntry.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapContainsEntryWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapContainsKey.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjMapContainsKeyWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjMapContainsEntryTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjMapContainsKeyTest.java
  changelog/@unreleased/pr-925.v2.yml
Labels: merge when ready

#930 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#927 Rule to refacter out String.format from describedAs
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjDescribedAsFormat.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjDescribedAsFormatTest.java
  changelog/@unreleased/pr-927.v2.yml
Labels: merge when ready

#931 Sort output of checkUnusedDependencies
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
Labels: merge when ready, no changelog

#942 Refaster rule 'CollectionStreamForEach'
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/CollectionStreamForEach.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/CollectionStreamForEachTest.java
  changelog/@unreleased/pr-942.v2.yml
Labels: merge when ready

#943 Fix #938: ExecutorSubmitRunnableFutureIgnored as error prone ERROR
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ExecutorSubmitRunnableFutureIgnored.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ExecutorSubmitRunnableFutureIgnoredTest.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/ExecutorSubmitRunnableFutureIgnored.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/ExecutorSubmitRunnableFutureIgnoredTest.java
  changelog/@unreleased/pr-943.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#944 Add `providesFix = REQUIRES_HUMAN_ATTENTION` to relevant checks
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocation.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySet.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionTransform.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferListsPartition.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptions.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggingPreconditions.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StringBuilderConstantParameters.java
Labels: merge when ready, no changelog

#951 checkJUnitDependencies also detects spock (via nebula-test)
  changelog/@unreleased/pr-951.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: autorelease, merge when ready

#933 Fix checkUnusedDependencies source-only configurations test
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready, no changelog

#952 Fix error-prone `UnnecessaryParentheses` by default
  changelog/@unreleased/pr-952.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#905 Add documentation about running refasterApply
  README.md
Labels: merge when ready, no changelog

#924 Use Mockito verifyNoInteractions over deprecated verifyZeroInteractions
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/MockitoVerifyNoInteractions.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/MockitoVerifyNoInteractionsTest.java
  changelog/@unreleased/pr-924.v2.yml
Labels: merge when ready

#958 Improve TestCheckUtils.isTestCode test detection
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/TestCheckUtils.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptionsTest.java
  changelog/@unreleased/pr-958.v2.yml
Labels: merge when ready

#957 Implement Error Prone `ThrowError` to discourage throwing Errors in production code
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowError.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ThrowErrorTest.java
  changelog/@unreleased/pr-957.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#962 Slf4jLevelCheck additional work
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLevelCheck.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLevelCheckTest.java
Labels: merge when ready, no changelog

#941 Added errorprone checks for Guavas static factory methods.
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionConstructors.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCollectionConstructorsTest.java
  changelog/@unreleased/pr-941.v2.yml
Labels: merge when ready, no changelog

#968 fix #967: Suppress error-prone PreferCollectionConstructors on jdk13
  changelog/@unreleased/pr-968.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#936 New feature flag: com.palantir.baseline-format.palantir-java-format=true
  README.md
  changelog/@unreleased/pr-936.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/BlankLines.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/Correct.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/Invalid.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/Multicatch.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/MultilineStringConstant.java
  versions.props
Labels: autorelease, merge when ready

#970 fix #969: Implement error prone ReverseDnsLookup for unexpected reverse dns lookups
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ReverseDnsLookupTest.java
  changelog/@unreleased/pr-970.v2.yml
Labels: autorelease, merge when ready

#975 Correctly rewrite verifyZeroInteractions
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/MockitoVerifyZeroInteractions.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/MockitoVerifyZeroInteractionsTest.java
  changelog/@unreleased/pr-975.v2.yml
Labels: merge when ready

#981 Restrict migration to safe-logging to source sets that have the library
  changelog/@unreleased/pr-981.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#978 ReadReturnValueIgnored: Check that read operation results are not ignored
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReadReturnValueIgnored.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ReadReturnValueIgnoredTest.java
  changelog/@unreleased/pr-978.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#986 palantir-java-format 0.2.3 -> 0.2.7
  versions.props
Labels: merge when ready, no changelog

#987 Less checkstyle.xml when palantir-java-format is enabled
  changelog/@unreleased/pr-987.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineConfigIntegrationTest.groovy
Labels: merge when ready

#989 Improvement: Load palantir-java-format dynamically
  changelog/@unreleased/pr-989.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/format/PalantirJavaFormatStep.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/MultilineStringConstant.java
  versions.props
Labels: autorelease, merge when ready

#988 Format diff task
  changelog/@unreleased/pr-988.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
Labels: autorelease, merge when ready

#994 One more AssertjOptionalIsNotPresent case
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsNotPresent.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsNotPresentWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjOptionalPresenceTest.java
Labels: merge when ready, no changelog

#948 Improve checkUnusedDependencies message
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready, no changelog

#998 Implement a suggested fix for CatchBlockLogException
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchBlockLogException.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchBlockLogExceptionTest.java
  changelog/@unreleased/pr-998.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1001 Slf4jLogsafeArgs fixes safe-log wrapped throwables
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgs.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgsTest.java
  changelog/@unreleased/pr-1001.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready
