Repository palantir/gradle-baseline, pull requests merged in 2019-11, with the labels that each got.

#1008 Implement `FinalClass` error prone check, replacing the checkstyle implementation
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FinalClass.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FinalClassTest.java
  changelog/@unreleased/pr-1008.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1010 Error prone validation to avoid redundant modifiers
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  changelog/@unreleased/pr-1010.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1011 FinalClass respects SafeVarargs annotation requirements
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FinalClass.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FinalClassTest.java
Labels: autorelease, merge when ready, no changelog

#1014 Fix `RedundantModifier` interpretation of implicit modifiers
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  changelog/@unreleased/pr-1014.v2.yml
Labels: autorelease, merge when ready

#1018 Validate suggested fixes pass validation
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchBlockLogExceptionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ExecutorSubmitRunnableFutureIgnoredTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FinalClassTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySetTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCollectionConstructorsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCollectionTransformTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferListsPartitionTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptionsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggingPreconditionsTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ReadReturnValueIgnoredTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RefactoringValidator.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ReverseDnsLookupTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLevelCheckTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StringBuilderConstantParametersTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ThrowErrorTest.java
Labels: merge when ready, no changelog

#1017 Fix RedundantModifier failures types nested in interfaces
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  changelog/@unreleased/pr-1017.v2.yml
Labels: autorelease, merge when ready

#1020 Fix error-prone mathcing literal null as a subtype.
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchBlockLogException.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousThrowableMessageSafeArg.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GradleCacheableTaskAction.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreMatchers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionTransform.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferListsPartition.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreventTokenLogging.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jConstantLogMessage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgs.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowError.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousThrowableMessageSafeArgTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgsTest.java
  changelog/@unreleased/pr-1020.v2.yml
Labels: merge when ready

#1023 Exclude Java 9 module-info.java
  changelog/@unreleased/pr-1023.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready

#1024 Fix typo
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/util/GitUtils.java
Labels: merge when ready, no changelog

#1021 Error prone RedundantModifier check supports more interface components
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreMatchers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  changelog/@unreleased/pr-1021.v2.yml
Labels: merge when ready

#1028 Drop RedundantModifier to SUGGESTION and FinalClass to WARNING
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FinalClass.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  changelog/@unreleased/pr-1028.v2.yml
Labels: merge when ready

#1027 fix #1025 Error Prone `StrictCollectionIncompatibleType` to guard collection usage
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictCollectionIncompatibleType.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictCollectionIncompatibleTypeTest.java
  changelog/@unreleased/pr-1027.v2.yml
Labels: autorelease, merge when ready

#1033 Assertj simplify assertions involving booleans
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjBooleanConjunction.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjBooleanConjunctionWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjIsFalse.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjIsFalseWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjIsTrue.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjIsTrueWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjBooleanConjunctionTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjIsFalseTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjIsTrueTest.java
Labels: merge when ready, no changelog

#1032 Error Prone InvocationHandlerDelegation to ensure proxies handle delegate exceptions.
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/InvocationHandlerDelegation.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreMatchers.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/InvocationHandlerDelegationTest.java
  changelog/@unreleased/pr-1032.v2.yml
Labels: autorelease, merge when ready

#1036 Move DangerousStringInternUsage message to BugPattern.summary annotation
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousStringInternUsage.java
Labels: merge when ready, no changelog

#1039 Add a refaster rule to migrate ITE getTargetException -> getCause
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/InvocationTargetExceptionCause.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/InvocationTargetExceptionCauseTest.java
  changelog/@unreleased/pr-1039.v2.yml
Labels: merge when ready

#1045 Fix: Unsanitized regex breaking errorprone on windows paths
  changelog/@unreleased/pr-1045.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1044 palantir-java-format 0.3.0 -> 0.3.2
  versions.props
Labels: merge when ready, no changelog

#1051 Relax SingleLineJavadoc to avoid fighting the formatter
  changelog/@unreleased/pr-1051.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready

#1052 PreferAssertj disallows `assert` statements in test code.
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-1052.v2.yml
Labels: autorelease, merge when ready

#1054 fix #1053 Implement `Slf4jThrowable` check to ensure throwable args are logged last
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jThrowable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jThrowableTest.java
  changelog/@unreleased/pr-1054.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1055 Add JooqResultStreamLeak ErrorProne rule
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JooqResultStreamLeak.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JooqResultStreamLeakTest.java
  changelog/@unreleased/pr-1055.v2.yml
  versions.props
Labels: autorelease, merge when ready

#1059 Refaster rule to remove unnecessary supplier creation
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SupplierRedefinition.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SupplierRedefinitionTest.java
  changelog/@unreleased/pr-1059.v2.yml
Labels: merge when ready

#1061 Refaster rule to convert Stream.of() -> Stream.empty()
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/StreamEmpty.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/StreamEmptyTest.java
  changelog/@unreleased/pr-1061.v2.yml
Labels: merge when ready

#1063 Revert "Refaster rule to remove unnecessary supplier creation (#1059)"
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SupplierRedefinition.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SupplierRedefinitionTest.java
  changelog/@unreleased/pr-1063.v2.yml
Labels: autorelease, merge when ready

#1064 Fix: Disable conflicting checkstyle rules if started migrating to PJF
  changelog/@unreleased/pr-1064.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineConfigIntegrationTest.groovy
Labels: autorelease, merge when ready

#1068 Replace refaster `StreamEmpty` with error prone `StreamOfEmpty`
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreSuggestedFixes.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StreamOfEmpty.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StreamOfEmptyTest.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/StreamEmpty.java
  changelog/@unreleased/pr-1068.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1069 RedundantMethodReference check to avoid unnecessary method references
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantMethodReferenceTest.java
  changelog/@unreleased/pr-1069.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1071 PreferAssertj iterable-map fix retains map type parameters
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-1071.v2.yml
Labels: merge when ready

#1078 refaster for assertThat(a == b)
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjPrimitiveEquals.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjPrimitiveEqualsWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjPrimitiveEqualsTest.java
  changelog/@unreleased/pr-1078.v2.yml
Labels: merge when ready

#1077 Fix grammar nit
  README.md
Labels: merge when ready, no changelog
