Repository palantir/gradle-baseline, pull requests merged in 2019-08, with the labels that each got.

#723 Fix readme
  README.md
Labels: no changelog

#724 Fix spotless apply with eclipse config
  changelog/@unreleased/pr-724.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
Labels: autorelease, merge when ready

#725 Junit5RuleUsage respects migration support
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JUnit5RuleUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JUnit5RuleUsageTest.java
  changelog/@unreleased/pr-725.v2.yml
Labels: autorelease, merge when ready

#729 IntelliJ GitHub issue navigation
  changelog/@unreleased/pr-729.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaTest.groovy
Labels: merge when ready

#716 Wrap long parameterized types where necessary
  changelog/@unreleased/pr-716.v2.yml
  gradle-baseline-java-config/resources/spotless/eclipse.xml
Labels: merge when ready

#727 Allow suppression of TODO checkstyle check
  .baseline/checkstyle/checkstyle.xml
  changelog/@unreleased/pr-727.v2.yml
Labels: merge when ready

#733 print out suggestion for module dependencies inclusion in useful format
  changelog/@unreleased/pr-733.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready

#739 Delete broken link
  docs/best-practices/code-reviews/readme.md
Labels: merge when ready, no changelog

#736 detect if dependency is actually the current project.
  changelog/@unreleased/pr-736.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready

#740 fix #737: Implement DangerousCompletableFutureUsage errorprone check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousCompletableFutureUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousCompletableFutureUsageTest.java
  changelog/@unreleased/pr-740.v2.yml
Labels: autorelease, merge when ready

#741 Refaster to use `execute` over `submit` when the result is ignored
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/ExecutorSubmitRunnableFutureIgnored.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/ExecutorSubmitRunnableFutureIgnoredTest.java
  changelog/@unreleased/pr-741.v2.yml
Labels: merge when ready

#742 Enable applying refaster rules for repos with -Xlint:deprecation
  changelog/@unreleased/pr-742.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneRefasterIntegrationTest.groovy
Labels: merge when ready

#750 Revert "Excavator: Upgrades Baseline to the latest version (#720)"
  .baseline/checkstyle/checkstyle.xml
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptions.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/OptionalOrElseSupplier.java
  build.gradle
Labels: merge when ready, no changelog

#751 Include more checks to be patched
  changelog/@unreleased/pr-751.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#718 Remove custom idea JDK configuration
  changelog/@unreleased/pr-718.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaIntegrationTest.groovy
Labels: merge when ready

#752 SortedFirst refactor implementation for no-arg `sort()`
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SortedFirstNatural.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SortedFirstNaturalTest.java
  changelog/@unreleased/pr-752.v2.yml
Labels: merge when ready

#753 Error prone validation that Stream.sort is invoked on comparable streams
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/NonComparableStreamSort.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/NonComparableStreamSortTests.java
  changelog/@unreleased/pr-753.v2.yml
Labels: merge when ready

#754 Fix #656 `DangerousStringInternUsage`: Disallow String.intern() invocations
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousStringInternUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousStringInternUsageTest.java
  changelog/@unreleased/pr-754.v2.yml
Labels: merge when ready

#757 Revert "Include more checks to be patched (#751)"
  changelog/@unreleased/revert-pr-751.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#756 fix #407: Disable errorprone `Slf4jLogsafeArgs` in test code
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgs.java
  changelog/@unreleased/pr-756.v2.yml
Labels: merge when ready

#755 fix #511: Remove redundant errorprone `LogSafePreconditionsConstantMessage`
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LogSafePreconditionsConstantMessage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LogSafePreconditionsConstantMessageTests.java
  changelog/@unreleased/pr-755.v2.yml
Labels: merge when ready

#758 Promote two error-prone checks to error
  changelog/@unreleased/pr-758.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#759 errorprone `OptionalOrElseThrowThrows` to prevent throwing in orElseThrow
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseThrowThrows.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseThrowThrowsTest.java
  changelog/@unreleased/pr-759.v2.yml
Labels: autorelease, merge when ready

#761 LogSafePreconditionsMessageFormat disallows slf4j-style format characters
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LogSafePreconditionsMessageFormat.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LogSafePreconditionsMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreconditionsTests.java
  changelog/@unreleased/pr-761.v2.yml
Labels: merge when ready

#763 Error Prone LambdaMethodReference check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  changelog/@unreleased/pr-763.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#766 Delete FindBugs
  changelog/@unreleased/pr-766.v2.yml
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/StyleTaskTimer.java
Labels: autorelease, merge when ready

#767 More Java 13 pre-reqs
  changelog/@unreleased/pr-767.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  versions.props
Labels: merge when ready

#769 Add SCM information to POM
  build.gradle
  changelog/@unreleased/pr-769.v2.yml
  gradle/publish-jar.gradle
Labels: autorelease, merge when ready

#771 LambdaMethodReference avoids suggestions for non-static methods
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  changelog/@unreleased/pr-771.v2.yml
Labels: autorelease, merge when ready

#773 Fix: Filter out pom only artifacts from dependnecies in checkUnusedDependencies
  changelog/@unreleased/pr-773.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
Labels: autorelease, merge when ready
