Repository palantir/gradle-baseline, pull requests merged in 2019-09, with the labels that each got.

#765 Eliminate some warnings/deprecations
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsage.java
  baseline-refaster-testing/src/main/java/com/palantir/baseline/refaster/RefasterTestHelper.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/CheckstyleReportHandler.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/StyleTaskTimer.java
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/JunitReportsFinalizerTests.java
Labels: merge when ready, no changelog

#783 checkUnusedDependencies handles compileOnly and annotationProcessor
  changelog/@unreleased/pr-783.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready

#790 Disable PreconditionsConstantMessage on gradle plugins
  changelog/@unreleased/pr-790.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#791 Break: Add gradle 6.0-20190904072820+0000 compatibility. Compile with -Werror and -Xlint:deprecation
  README.md
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompiler.java
  build.gradle
  changelog/@unreleased/pr-791.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/versions/CheckBomConflictTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/versions/CheckNoUnusedPinTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIntegrationTest.groovy
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsExtension.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsFinalizer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsPlugin.java
Labels: merge when ready

#794 baseline-idea: configures IntelliJ EclipseCodeFormatter plugin
  changelog/@unreleased/pr-794.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#793 Fix: don't apply error prone patches for disabled checks
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptions.java
  changelog/@unreleased/pr-793.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: autorelease, merge when ready

#775 baseline-circleci: Ensures root project name is specified
  changelog/@unreleased/pr-775.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCircleCi.java
Labels: merge when ready

#798 Remove jgit dependency
  changelog/@unreleased/pr-798.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/util/GitUtils.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaTest.groovy
  versions.props
Labels: autorelease, merge when ready

#807 Fix: eclipse formatter multicatch alignment passes checkstyle
  changelog/@unreleased/pr-807.v2.yml
  gradle-baseline-java-config/resources/spotless/eclipse.xml
Labels: autorelease, merge when ready

#808 Eclipse formatter integration test
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-expected/BlankLines.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-expected/Correct.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-expected/Invalid.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-expected/Multicatch.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/BlankLines.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/Correct.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/Invalid.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/Multicatch.java
Labels: merge when ready, no changelog

#810 Fix: classpath uniqueness checks runtimeClasspath by default
  changelog/@unreleased/pr-810.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
Labels: autorelease, merge when ready

#815 SafeLoggingExceptionMessageFormat disallows {} in safelog exception messages
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SafeLoggingExceptionMessageFormat.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/SafeLoggingExceptionMessageFormatTests.java
  changelog/@unreleased/pr-815.v2.yml
Labels: merge when ready

#821 Message format checks use instanceof rather than catching
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreconditionsMessageFormat.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SafeLoggingExceptionMessageFormat.java
  changelog/@unreleased/pr-821.v2.yml
Labels: merge when ready

#819 Strict unused variable check
  .baseline/checkstyle/custom-suppressions.xml
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-819.v2.yml
Labels: autorelease, merge when ready

#823 ignore module-info.class when checking class uniqueness
  changelog/@unreleased/pr-823.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/ClassUniquenessAnalyzer.java
Labels: autorelease, merge when ready

#830 Fix: Checkstyle no longer verifies resources
  changelog/@unreleased/pr-830.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCheckstyle.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCheckstyleTest.groovy
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/XmlReportFailuresSupplier.java
Labels: autorelease, merge when ready

#828 Fix compilation of baseline-error-prone to be deterministic
  baseline-error-prone/build.gradle
  build.gradle
Labels: merge when ready, no changelog

#829 Fix: add reference link to StrictUnusedVariable check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  changelog/@unreleased/pr-829.v2.yml
Labels: merge when ready

#835 Fix: Long try-with-resources adheres to palantir style
  changelog/@unreleased/pr-835.v2.yml
  gradle-baseline-java-config/resources/spotless/eclipse.xml
  gradle-baseline-java/src/test/resources/com/palantir/baseline/googlejavaformat-expected/B21465217.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/googlejavaformat-expected/TryWithResources.java
Labels: autorelease, merge when ready

#832 Fix #831: Error Prone StringBuilderConstantParameters
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StringBuilderConstantParameters.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StringBuilderConstantParametersTests.java
  changelog/@unreleased/pr-832.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#827 baseline-refaster-rules can be overridden
  baseline-error-prone/build.gradle
  changelog/@unreleased/pr-827.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneRefasterIntegrationTest.groovy
Labels: merge when ready

#841 ErrorProne PreferAssertj migration to AssertJ from org.junit.Assert
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-841.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#843 new JUnit5SuiteMisuse error-prone check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousParallelStreamUsage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousStringInternUsage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousThreadPoolExecutorUsage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GuavaPreconditionsMessageFormat.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JUnit5RuleUsage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JUnit5SuiteMisuse.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/NonComparableStreamSort.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreconditionsConstantMessage.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StringBuilderConstantParameters.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ValidateConstantMessage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JUnit5SuiteMisuseTest.java
  changelog/@unreleased/pr-843.v2.yml
Labels: merge when ready

#833 Autofix StrictUnusedVariable
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-833.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#848 README mentions iterating on eclipse.xml
  README.md
Labels: merge when ready, no changelog

#853 Errorprone ignores code in build directory
  changelog/@unreleased/pr-853.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#850 PreferAssertj provides better hamcrest replacements
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-850.v2.yml
Labels: autorelease, merge when ready

#859 Fix hamcrest arrayContainingInAnyOrder conversion
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-859.v2.yml
Labels: autorelease, merge when ready

#854 strictUnusedVariable only support _ suppression prefix
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-854.v2.yml
Labels: merge when ready

#861 People have to opt-in to PreferAssertj patching
  changelog/@unreleased/pr-861.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#864 Errorprone ignores all generated code
  changelog/@unreleased/pr-864.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#865 Correctly fix previous suppressed params
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-865.v2.yml
Labels: merge when ready

#870 StrictUnusedVariable maintains side effects
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-870.v2.yml
Labels: merge when ready

#863 Formatter preserves NLS comments in multiline string constants
  gradle-baseline-java-config/resources/spotless/eclipse.xml
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-expected/MultilineStringConstant.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/MultilineStringConstant.java
Labels: merge when ready, no changelog

#851 Some low-effort AssertJ refasters
  .baseline/checkstyle/custom-suppressions.xml
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSizeExactly.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSizeGreaterThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionIsEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionIsNotEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjFileContent.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsPresent.java
  changelog/@unreleased/pr-851.v2.yml
Labels: merge when ready

#837 New checkJUnitDependencies task
  README.md
  changelog/@unreleased/pr-837.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: merge when ready

#874 Avoid ambiguity in assertions on iterable maps
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-874.v2.yml
Labels: merge when ready

#877 StringBuilderConstantParameters suggested fix doesn't remove comments
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StringBuilderConstantParameters.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StringBuilderConstantParametersTests.java
  changelog/@unreleased/pr-877.v2.yml
Labels: merge when ready

#876 Improve AssertjCollectionIsEmpty and add test cases
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionIsEmpty.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjCollectionIsEmptyTest.java
Labels: merge when ready, no changelog

#875 Improve performannce of error prone PreferAssertj check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  changelog/@unreleased/pr-875.v2.yml
Labels: merge when ready

#878 Fix stalebot config
  .github/stale.yml
Labels: merge when ready, no changelog

#880 Less strict junit dependency check
  changelog/@unreleased/pr-880.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: autorelease, merge when ready

#883 PreferAssertj supports migration of zero-delta floating point array asserts
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java
  changelog/@unreleased/pr-883.v2.yml
Labels: merge when ready

#885 checkJunitDependencies only checks Java source
  changelog/@unreleased/pr-885.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
Labels: autorelease, merge when ready

#887 AssertJ Refaster fixes use static `assertThat` imports
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSizeExactly.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSizeGreaterThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionIsNotEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjFileContent.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsPresent.java
  changelog/@unreleased/pr-887.v2.yml
Labels: autorelease, merge when ready

#888 Disable `UnusedVariable` in favour of `StrictUnusedVariable`
  changelog/@unreleased/pr-888.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#892 Fix error-prone suppressions with JUnit5 @TestTemplate
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/TestCheckUtils.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptionsTest.java
  changelog/@unreleased/pr-892.v2.yml
Labels: merge when ready

#896 BaselineFormat task exclude generated code on Windows
  changelog/@unreleased/pr-896.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
Labels: autorelease, merge when ready

#898 Refaster rules for AssertJ tests
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjEquals.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjEqualsWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjInstanceOf.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjInstanceOfWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjNotEquals.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjNotEqualsWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjStringContains.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjStringContainsWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjStringDoesNotContain.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjStringDoesNotContainWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjEqualityTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjInstanceOfTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjStringContentTest.java
  changelog/@unreleased/pr-898.v2.yml
Labels: merge when ready

#900 refaster for assertj hasSameSizeAs
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjCollectionHasSameSizeAs.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjCollectionHasSameSizeAsTest.java
  changelog/@unreleased/pr-900.v2.yml
Labels: merge when ready

#902 keep spotless from eagerly configuring all tasks.
  changelog/@unreleased/pr-902.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatTest.groovy
Labels: merge when ready

#906 Fix refaster compileation on gradle 5.x
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CompileRefasterTask.java
Labels: merge when ready, no changelog

#904 Continue when RefasterRuleBuilderScanner throws
  baseline-refaster-javac-plugin/build.gradle
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompilerAnalyzer.java
  changelog/@unreleased/pr-904.v2.yml
Labels: merge when ready

#907 update changelog
  changelog/@unreleased/refaster-gradle-6.v2.yml
Labels: autorelease, merge when ready, no changelog

#908 Remove bad log line
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CompileRefasterTask.java
Labels: no changelog

#910 Added Refaster Rule for Optional 'hasValue' Assert
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValue.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValueWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjOptionalHasValueTest.java
  changelog/@unreleased/refaster-rule-optional-hasvalue.v2.yml
Labels: merge when ready

#912 AssertJ refasters for some integer inequalities
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanOrEqualTo.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanOrEqualToWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjGreaterThanWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThan.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanOrEqualTo.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanOrEqualToWithDescription.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjLessThanWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjInequalitiesTest.java
Labels: merge when ready, no changelog

#911 Add refaster rule to simplify empty optional asserts
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsNotPresent.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalIsNotPresentWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjOptionalPresenceTest.java
  changelog/@unreleased/pr-911.v2.yml
Labels: merge when ready

#914 More refasters for AssertJ optional hasValue method
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValue.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjOptionalHasValueWithDescription.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjOptionalHasValueTest.java
Labels: merge when ready, no changelog

#913 Assertj refasters for array equality
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AssertjArrayEquals.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AssertjArrayEqualsTest.java
Labels: merge when ready, no changelog

#915 Allow static imports of AssertJ and Mockito
  changelog/@unreleased/pr-915.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready
