Repository palantir/gradle-baseline, pull requests merged in 2020-10, with the labels that each got.

#1504 Errorprone rule to check that all fields in immutables builders have been initialized
  .gitignore
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitialization.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitializationTest.java
  changelog/@unreleased/pr-1504.v2.yml
Labels: autorelease, merge when ready

#1507 Fix ImmutablesBuilderMissingInitialization on Java 15 when immutables isn't on the classpath
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitialization.java
  changelog/@unreleased/pr-1507.v2.yml
Labels: autorelease, merge when ready

#1510 error-prone UnnecessarilyQualified
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnnecessarilyQualified.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessarilyQualifiedTest.java
  changelog/@unreleased/pr-1510.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1513 disable PlaceholderCountMatchesArgumentCount
  changelog/@unreleased/pr-1513.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1514 Promote BoxedPrimitiveEquality and ReferenceEquality
  changelog/@unreleased/pr-1514.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1519 Fix NPE when checking immutables builders from abstract methods
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitialization.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitializationTest.java
  changelog/@unreleased/pr-1519.v2.yml
Labels: autorelease, merge when ready

#1521 Implement DeprecatedGuavaObjects error-prone migration
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DeprecatedGuavaObjects.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DeprecatedGuavaObjectsTest.java
  changelog/@unreleased/pr-1521.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1522 Implement error-prone ObjectsHashCodeUnnecessaryVarargs migration
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ObjectsHashCodeUnnecessaryVarargs.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ObjectsHashCodeUnnecessaryVarargsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RefactoringValidator.java
  changelog/@unreleased/pr-1522.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1523 Automatically fix occurrences of `ObjectsHashCodePrimitive`
  changelog/@unreleased/pr-1523.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1524 Always set JVM 8 target in Scala compiler
  changelog/@unreleased/pr-1524.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineScalastyle.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineScalastyleTest.groovy
Labels: autorelease, merge when ready

#1525 Fix: fix changelog for pr 1542
  changelog/@unreleased/pr-1524.v2.yml
Labels: autorelease, merge when ready, no changelog

#1528 Use old version-string scheme for Scala compiler target
  changelog/@unreleased/pr-1528.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineScalastyle.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineScalastyleTest.groovy
Labels: autorelease, merge when ready
