Repository palantir/gradle-baseline, pull requests merged in 2020-01, with the labels that each got.

#1139 Migrate the CollectionStreamForEach refactor to error-prone
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CollectionStreamForEach.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CollectionStreamForEachTest.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/CollectionStreamForEach.java
  changelog/@unreleased/pr-1139.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1144 Enable optimizing imports on the fly by default
  changelog/@unreleased/pr-1144.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1145 New baseline-class-uniqueness.lock file allows incremental adoption
  README.md
  changelog/@unreleased/pr-1145.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/rules/BaselineClassUniquenessRule.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckClassUniquenessTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/ClassUniquenessAnalyzer.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/baseline-class-uniqueness.expected.lock
Labels: autorelease, merge when ready

#1146 Exempt slf4j logger from unused field removal
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
Labels: merge when ready, no changelog

#1151 IntelliJ: Format on save when using PJF
  changelog/@unreleased/pr-1151.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/GroovyXmlUtils.groovy
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/XmlUtils.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/AbstractPluginTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaIntegrationTest.groovy
Labels: autorelease, merge when ready

#1153 baseline-class-uniqueness is updated by `./gradlew --write-locks`
  changelog/@unreleased/pr-1153.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
Labels: autorelease, merge when ready

#1158 Fix: baseline-idea correctly filters save actions to java files
  changelog/@unreleased/pr-1158.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1160 Fix #1159: StrictUnusedVariable respects UnusedVariable suppression
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1160.v2.yml
Labels: autorelease, merge when ready

#1164 Remove dead link from testing-software best practices readme
  docs/best-practices/testing-software/readme.md
Labels: merge when ready, no changelog

#1163 fix #1161: Add error prone LoggerEnclosingClass
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LoggerEnclosingClassTest.java
  changelog/@unreleased/pr-1163.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease

#1171 Fix `LoggerEnclosingClass` edge cases for type parameters and anonymous classes
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LoggerEnclosingClassTest.java
  changelog/@unreleased/pr-1171.v2.yml
Labels: autorelease, merge when ready

#1176 Fix 6.1 checkstyle report finalizer failure
  changelog/@unreleased/pr-1176.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCheckstyle.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/JunitReportsPluginSpec.groovy
  gradle-junit-reports/build.gradle
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsFinalizer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/XmlReportFailuresSupplier.java
Labels: autorelease, merge when ready

#1185 Fix #1182: Don't run baseline-error-prone tests concurrently
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchBlockLogExceptionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousCompletableFutureUsageTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousParallelStreamUsageTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousStringInternUsageTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousThreadPoolExecutorUsageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousThrowableMessageSafeArgTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FinalClassTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GradleCacheableTaskActionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GuavaPreconditionsConstantMessageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GuavaPreconditionsMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/InvocationHandlerDelegationTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JUnit5RuleUsageTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JUnit5SuiteMisuseTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JooqResultStreamLeakTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LogSafePreconditionsMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/NonComparableStreamSortTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseMethodInvocationTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/OptionalOrElseThrowThrowsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySetTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCollectionConstructorsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCollectionTransformTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferListsPartitionTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggingPreconditionsTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreventTokenLoggingTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantMethodReferenceTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ReverseDnsLookupTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/SafeLoggingExceptionMessageFormatTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ShutdownHookTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jConstantLogMessageTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLevelCheckTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLogsafeArgsTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jThrowableTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StreamOfEmptyTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictCollectionIncompatibleTypeTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StringBuilderConstantParametersTests.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/SwitchStatementDefaultCaseTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ThrowErrorTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ValidateConstantMessageTests.java
Labels: merge when ready, no changelog

#1184 baseline-circleci no longer applies configuration resolver plugin
  README.md
  changelog/@unreleased/no-more-configuration-resolver.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCircleCi.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCircleCiIntegrationTest.groovy
  versions.lock
  versions.props
Labels: merge when ready

#1186 fix #894: Error Prone UnnecessaryLambdaArgumentParentheses
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnnecessaryLambdaArgumentParentheses.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessaryLambdaArgumentParenthesesTest.java
  changelog/@unreleased/pr-1186.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1192 Fix `UnnecessaryLambdaArgumentParentheses` handling primitive lambda args
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnnecessaryLambdaArgumentParentheses.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessaryLambdaArgumentParenthesesTest.java
  changelog/@unreleased/pr-1192.v2.yml
Labels: autorelease, merge when ready
