Repository palantir/gradle-baseline, pull requests merged in 2020-11, with the labels that each got.

#1530 Fix baseline-idea inspection configuration
  changelog/@unreleased/pr-1530.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1529 Idea highlights calls to incubating conjure endpoints
  changelog/@unreleased/pr-1529.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1531 Add error-prone check for system time zone usage
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JavaTimeSystemDefaultTimeZone.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JavaTimeSystemDefaultTimeZoneTest.java
  changelog/@unreleased/pr-1531.v2.yml
Labels: autorelease, merge when ready

#1532 Automatically fix JavaTimeSystemDefaultTimeZone
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready, no changelog

#1533 Allow ErrorProne to qualify JavaTimeSystemDefaultTimeZone fix types
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JavaTimeSystemDefaultTimeZone.java
Labels: merge when ready, no changelog

#1537 Update maven-dependency-analyzer
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#1534 Update spotless to 5.7.0
  README.md
  changelog/@unreleased/pr-1534.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/BlankLines.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1542 Disable --release flag when --add-exports is used
  README.md
  changelog/@unreleased/pr-1542.v2.yml
  docs/best-practices/code-reviews/readme.md
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineReleaseCompatibility.java
Labels: autorelease, merge when ready

#1546 checkstyle 8.36 -> 8.37 (and keep it up to date using excavator)
  changelog/@unreleased/pr-1546.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCheckstyle.java
  gradle-baseline-java/src/main/resources/checkstyle.version
  versions.props
Labels: autorelease, merge when ready

#1549 New plugin: 'com.palantir.baseline-enable-preview-flag'
  README.md
  changelog/@unreleased/pr-1549.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineEnablePreviewFlag.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-enable-preview-flag.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineEnablePreviewFlagTest.groovy
Labels: autorelease, merge when ready

#1551 Fix regression in ./gradlew idea introduced in baseline 3.51.0
  changelog/@unreleased/pr-1551.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaIntegrationTest.groovy
Labels: autorelease, merge when ready

#1554 Add `PreventUsingIncubatingMethods` error-prone check (conjure)
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/IncubatingMethod.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/IncubatingMethodTest.java
  changelog/@unreleased/pr-1554.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1557 Improve the DangerousJsonTypeInfoUsage check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousJsonTypeInfoUsageTests.java
  changelog/@unreleased/pr-1557.v2.yml
Labels: autorelease, merge when ready

#1553 Apply baseline-class-unqiueness by default
  changelog/@unreleased/pr-1553.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTest.groovy
Labels: autorelease, merge when ready

#1561 baseline-format: can format build.gradle files
  README.md
  changelog/@unreleased/pr-1561.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/resources/greclipse.properties
Labels: autorelease, merge when ready

#1565 Fix unit tests on java 15
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FallThroughTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessaryParenthesesTest.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineEnablePreviewFlagTest.groovy
Labels: merge when ready, no changelog

#1559 Add error-prone CompileTimeConstantViolatesLiskovSubstitution check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CompileTimeConstantViolatesLiskovSubstitution.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CompileTimeConstantViolatesLiskovSubstitutionTest.java
  changelog/@unreleased/pr-1559.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1568 Fix path sensitivity of compile tasks
  changelog/@unreleased/pr-1568.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1571 Exclude generated sources from error-prone
  changelog/@unreleased/pr-1571.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineErrorProneTest.groovy
Labels: merge when ready

#1574 baseline-reproducibility validates that sourceCompatibility is set explicitly
  changelog/@unreleased/pr-1574.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineReproducibility.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckExplicitSourceCompatibilityTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineReproducibilityIntegrationSpec.groovy
Labels: autorelease, merge when ready

#1576 Saner test event logging default for CI
  changelog/@unreleased/pr-1576.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: autorelease, merge when ready
