Repository palantir/gradle-baseline, pull requests merged in 2020-03, with the labels that each got.

#1273 Add back checkUnusedDependencies.ignore and checkImplicitDependencies.ignore
  changelog/@unreleased/pr-1273.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesParentTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesParentTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
Labels: autorelease, merge when ready

#1274 Don't apply BaselineFixGradleJava by default
  changelog/@unreleased/pr-1274.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
Labels: merge when ready

#1275 Fix regression in baseline-exact-dependencies causing CME
  changelog/@unreleased/pr-1275.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease, merge when ready

#1278 Disable left curl when using palantir-java-format
  changelog/@unreleased/pr-1278.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
Labels: autorelease, merge when ready

#1283 Fix class uniqueness non-deterministic ordering
  changelog/@unreleased/pr-1283.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
Labels: autorelease, merge when ready

#1287 Remove configuration name in exact dependencies suggestions
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready, no changelog

#1292 Disable catch specificity by default
  changelog/@unreleased/pr-1292.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1303 RedundantModifier check validates and fixes final parameters in abstract methods
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RedundantModifierTest.java
  changelog/@unreleased/pr-1303.v2.yml
  docs/best-practices/code-reviews/readme.md
  docs/best-practices/java-coding-guidelines/readme.md
Labels: autorelease, merge when ready

#1302 Fix checkstyle even if com.palantir.java-format is not applied directly
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
Labels: merge when ready, no changelog
