Repository palantir/gradle-baseline, pull requests merged in 2020-05, with the labels that each got.

#1309 Remove SwitchStatementDefaultCase error-prone check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SwitchStatementDefaultCase.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/SwitchStatementDefaultCaseTest.java
  changelog/@unreleased/pr-1309.v2.yml
Labels: autorelease, merge when ready

#1338 Fix unused dependencies breaking with gradle 6.4
  changelog/@unreleased/pr-1338.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease, merge when ready

#1341 Insert inner class imports in Intellij
  changelog/@unreleased/pr-1341.v2.yml
  gradle-baseline-java-config/resources/idea/intellij-java-palantir-style.xml
Labels: autorelease, merge when ready

#1347 Actually insert inner class imports
  gradle-baseline-java-config/resources/idea/intellij-java-palantir-style.xml
Labels: autorelease, no changelog

#1350 Stop IntelliJ suggesting commonly shaded packages
  changelog/@unreleased/pr-1350.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: autorelease, merge when ready

#1355 Strict unused variable enforces lambda parameters
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1355.v2.yml
Labels: autorelease, merge when ready

#1358 Fix strict unused lambda
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1358.v2.yml
Labels: autorelease, merge when ready

#1362 fix up potential visibility bug in suggested fixes
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
Labels: merge when ready

#1363 Fix for method references with type parameters
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
Labels: merge when ready

#1359 Rewrite lambdas to method references for instance methods
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  changelog/@unreleased/pr-1359.v2.yml
Labels: autorelease, merge when ready

#1322 Provider implicit toString
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GradleProviderToString.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GradleProviderToStringTest.java
  changelog/@unreleased/pr-1322.v2.yml
Labels: autorelease, merge when ready

#1367 Upgrade asm to support JDK14
  changelog/@unreleased/pr-1367.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1369 Ckozak/fo/lambda methods/fix
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
Labels: merge when ready
