Repository palantir/gradle-baseline, pull requests merged in 2020-02, with the labels that each got.

#1197 Add an ErrorProne check for raw types
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RawTypes.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/RawTypesTest.java
  changelog/@unreleased/pr-1197.v2.yml
Labels: autorelease, merge when ready

#1205 Turn off ParenPad when p-j-f enabled
  changelog/@unreleased/pr-1205.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineConfigIntegrationTest.groovy
Labels: autorelease, merge when ready

#1210 Turn off UnnecessaryLambda check in tests
  changelog/@unreleased/pr-1210.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1213 -Pcom.palantir.baseline-error-prone.disable
  changelog/@unreleased/pr-1213.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-versions.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: autorelease, merge when ready

#1220 ./gradlew test -Drecreate=true
  README.md
  changelog/@unreleased/pr-1220.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
Labels: merge when ready

#1217 License derived from .baseline/copyright
  README.md
  changelog/@unreleased/pr-1217.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/LazyFormatterStep.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/MultiLicenseHeaderStep.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatCopyrightIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
Labels: autorelease, merge when ready

#1227 License replacement attempts to preserve existing year info
  changelog/@unreleased/pr-1227.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/MultiLicenseHeaderStep.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatCopyrightIntegrationTest.groovy
Labels: autorelease, merge when ready

#1228 Don't trim license template lines
  changelog/@unreleased/pr-1228.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/MultiLicenseHeaderStep.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatCopyrightIntegrationTest.groovy
Labels: autorelease, merge when ready

#1232 Separate additional copyright
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/MultiLicenseHeaderStep.java
Labels: merge when ready, no changelog

#1250 checkClassUniqueness works with conjure
  changelog/@unreleased/pr-1250.v2.yml
  docs/best-practices/java-coding-guidelines/readme.md
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIntegrationTest.groovy
Labels: autorelease, merge when ready

#1254 New plugin BaselineFixGradleJava
  README.md
  changelog/@unreleased/pr-1254.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFixGradleJava.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-fix-gradle-java.properties
Labels: autorelease, merge when ready

#1260 baseline-exact-dependencies stops resolving compileOnly
  changelog/@unreleased/pr-1260.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease, merge when ready

#1253 Migrate VisibleForTesting validation from checkstyle to errorprone
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/VisibleForTestingPackagePrivate.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/VisibleForTestingPackagePrivateTest.java
  changelog/@unreleased/pr-1253.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: autorelease, merge when ready

#1262 BaselineExactDependencies applies to all source sets
  changelog/@unreleased/pr-1262.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease

#1267 Fix check dependencies
  changelog/@unreleased/pr-1267.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease, merge when ready
