Repository palantir/gradle-baseline, pull requests merged in 2020-06, with the labels that each got.

#1370 Improvement: Upgrade error-prone to 2.4.0
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CollectionStreamForEach.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ExecutorSubmitRunnableFutureIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreASTHelpers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreSuggestedFixes.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalFlatMapOfNullable.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySet.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionConstructors.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionTransform.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferListsPartition.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggingPreconditions.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RawTypes.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReadReturnValueIgnored.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ReverseDnsLookup.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLevelCheck.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StreamOfEmpty.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictCollectionIncompatibleType.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowError.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnsafeGaugeRegistration.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchSpecificityTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnsafeGaugeRegistrationTest.java
  changelog/@unreleased/pr-1370.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1371 Upgrade gradle-errorprone
  README.md
  changelog/@unreleased/pr-1371.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1372 validate against ambiguous references
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
Labels: merge when ready

#1365 Convert multi param lambdas and local method invocations to method references
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LambdaMethodReferenceTest.java
  changelog/@unreleased/pr-1365.v2.yml
Labels: autorelease, merge when ready

#1375 auto-fix PublicConstructorForAbstractClass
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, no changelog

#1381 Auto-fix ProtectedMembersInFinalClass
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, no changelog

#1380 Don't include SUGGESTION checks in default checks
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferBuiltInConcurrentKeySet.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantMethodReference.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/RedundantModifier.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StreamOfEmpty.java
  changelog/@unreleased/pr-1380.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1374 Add explicit asm dep
  changelog/@unreleased/pr-1374.v2.yml
  gradle-baseline-java/build.gradle
Labels: autorelease, merge when ready

#1379 Improvement: Add error-prone check that forbids extending java.lang.Error
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ExtendsErrorOrThrowable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ExtendsErrorOrThrowableTest.java
  changelog/@unreleased/pr-1379.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready

#1387 Auto-fix BadImport
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready, no changelog

#1386 Enable PreferCollectionConstructors by default
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCollectionConstructors.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ThrowSpecificity.java
  changelog/@unreleased/pr-1386.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1396 Add errorprone check for immutables style collisions
  README.md
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyleCollision.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesStyleCollisionTest.java
  changelog/@unreleased/pr-1396.v2.yml
Labels: autorelease, merge when ready

#1389 --write-locks no longer implicitly runs checkClassUniqueness task
  changelog/@unreleased/pr-1389.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
Labels: autorelease, merge when ready

#1404 Improvement: Upgrade Checkstyle to 8.33
  changelog/@unreleased/pr-1404.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCheckstyle.java
Labels: autorelease, merge when ready

#1409 Fix: Adjust checkstyle config for new version
  changelog/@unreleased/pr-1409.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: autorelease, merge when ready

#1412 StrictUnusedVariable handles Java 14 records
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1412.v2.yml
Labels: autorelease, merge when ready

#1416 Don't wrap method declaration
  changelog/@unreleased/pr-1416.v2.yml
  gradle-baseline-java-config/resources/spotless/eclipse.xml
  gradle-baseline-java/src/test/resources/com/palantir/baseline/eclipse-formatter-expected/FunctionDeclaration.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/formatter-in/FunctionDeclaration.java
  gradle-baseline-java/src/test/resources/com/palantir/baseline/palantirjavaformat-expected/FunctionDeclaration.java
Labels: autorelease, merge when ready

#1411 Improve gradle-baseline-java integration with IntelliJ import
  changelog/@unreleased/pr-1411.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/XmlUtils.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIdeaIntegrationTest.groovy
Labels: autorelease, merge when ready

#1420 fix changelog
  changelog/@unreleased/pr-1394.v2.yml
Labels: autorelease, merge when ready

#1426 Check unused dependencies task can be up to date
  changelog/@unreleased/pr-1426.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: autorelease, merge when ready

#1427 check junit dependencies task can be skipped
  changelog/@unreleased/pr-1427.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
Labels: autorelease

#1413 Disable broken rule on switch expressions
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessaryParenthesesTest.java
  changelog/@unreleased/pr-1413.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready
