Repository palantir/gradle-baseline, pull requests merged in 2021-06, with the labels that each got.

#1778 Fix: Correctly expose junit-reports plugin
  changelog/@unreleased/pr-1778.v2.yml
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/JunitReportsPluginSpec.groovy
  gradle-junit-reports/src/main/resources/META-INF/gradle-plugins/com.palantir.junit-reports.properties
Labels: autorelease, merge when ready

#1727 Require meta-annotations with source rentetion for Immutables styles
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyle.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesStyleCollisionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesStyleTest.java
  changelog/@unreleased/pr-1727.v2.yml
Labels: merge when ready

#1781 Fix ImmutablesStyle check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyle.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesStyleTest.java
Labels: autorelease, merge when ready, no changelog

#1782 fix typo in summary
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyle.java
Labels: merge when ready, no changelog

#1784 Suppress immutables check on tests
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitializationTest.java
Labels: merge when ready, no changelog

#1785 Checkstyle 8.43 JavadocMethod uses accessModifiers instead of scope
  .baseline/checkstyle/checkstyle.xml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready

#1788 Ban the var keyword via error-prone `VarUsage`
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/VarUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/VarUsageTest.java
  changelog/@unreleased/pr-1788.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1789 Fix VarUsage false positives in lambdas
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/VarUsage.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/VarUsageTest.java
  changelog/@unreleased/pr-1789.v2.yml
Labels: autorelease, merge when ready

#1802 Fix version badge
  README.md
Labels: merge when ready, no changelog

#1810 ban assert
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/BadAssert.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/BadAssertTest.java
  changelog/@unreleased/pr-1810.v2.yml
Labels: autorelease, merge when ready

#1813 Increase default test heap from 512m to 2g
  changelog/@unreleased/pr-1813.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTestHeap.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-test-heap.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestHeapTest.groovy
Labels: autorelease, merge when ready
