Repository palantir/gradle-baseline, pull requests merged in 2021-08, with the labels that each got.

#1863 recommend witchcraft logging
  changelog/@unreleased/pr-1863.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: merge when ready, autorelease

#1866 PreferSafeLogger produces suggestions which compile with >10 args
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLogger.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggerTest.java
  changelog/@unreleased/pr-1866.v2.yml
Labels: merge when ready, autorelease

#1868 Use `com.palantir.external-publish-gradle-plugin` in gradle-baseline-java
  gradle-baseline-java/build.gradle
Labels: merge when ready, autorelease, no changelog

#1870 witchcraft-logging functionality has been migrated
  changelog/@unreleased/pr-1870.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: merge when ready, autorelease

#1873 Automatically fix upstream `LoopOverCharArray`
  changelog/@unreleased/pr-1873.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease

#1879 JavaDoc uses UTF-8 encoding
  changelog/@unreleased/pr-1879.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineEncoding.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEncodingIntegrationTest.groovy
Labels: merge when ready, autorelease

#1876 Enforce PreferSafeLogger at `WARNING` level
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLogger.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggerTest.java
  changelog/@unreleased/pr-1876.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#1883 Re-add null check for exclude rule
  changelog/@unreleased/pr-1883.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
Labels: merge when ready, autorelease

#1884 Fix missing setProperty error when using Gradle 6
  changelog/@unreleased/pr-1884.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/AbstractBaselinePlugin.groovy
Labels: merge when ready, autorelease

#1886 Implement LoggerInterpolationConsumesThrowable
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerInterpolationConsumesThrowable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LoggerInterpolationConsumesThrowableTest.java
  changelog/@unreleased/pr-1886.v2.yml
Labels: merge when ready, autorelease

#1890 Java compilation warnings and errors are no longer limited to the first 100
  changelog/@unreleased/pr-1890.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineJavaCompilerDiagnostics.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-java-compiler-diagnostics.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaCompilerDiagnosticsTest.groovy
Labels: merge when ready, autorelease
