Repository palantir/gradle-baseline, pull requests merged in 2021-07, with the labels that each got.

#1816 Upgrade ProxyNonConstantType to WARNING (from suggestion)
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ProxyNonConstantType.java
  changelog/@unreleased/pr-1816.v2.yml
Labels: autorelease, merge when ready

#1820 Enable ConsistentOverrides by default
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ConsistentOverrides.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ConsistentOverridesTest.java
  changelog/@unreleased/pr-1820.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready

#1827 ProxyNonConstantType documents describe suppression cases and steps
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ProxyNonConstantType.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ProxyNonConstantTypeTest.java
  changelog/@unreleased/pr-1827.v2.yml
Labels: autorelease, merge when ready

#1824 Add Gradle 7 support
  changelog/3.99.0-rc1/pr-1824.v2.yml
  changelog/@unreleased/pr-1824.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFixGradleJava.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineReleaseCompatibility.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckExplicitSourceCompatibilityTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CompileRefasterTask.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-fix-gradle-java.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineFormatIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineReleaseCompatibilityIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineTestingIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/GradleTestVersions.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsPlugin.java
  versions.lock
  versions.props
Labels: merge when ready

#1832 Drop Bintray references from `README.md`
  README.md
Labels: merge when ready, no changelog

#1833 Remove baseline-fix-gradle-java readme section
  README.md
Labels: merge when ready, no changelog

#1839 Replace deprecated Report.enabled property
  changelog/@unreleased/pr-1839.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCircleCi.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/CheckstyleReportHandler.java
Labels: autorelease, merge when ready

#1838 Fix formatting of baseline-class-uniqueness.lock files
  changelog/@unreleased/pr-1838.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
Labels: merge when ready

#1834 Support the new SafeLogger API
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ConsistentLoggerName.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLogger.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jLevelCheck.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ConsistentLoggerNameTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/LoggerEnclosingClassTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggerTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/Slf4jLevelCheckTest.java
  changelog/@unreleased/pr-1834.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  versions.lock
Labels: autorelease, merge when ready

#1842 Allow `PreferSafeLogger` to migrate uses with level-checks
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLogger.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggerTest.java
  changelog/@unreleased/pr-1842.v2.yml
Labels: autorelease, merge when ready

#1843 fix NPE on unused lambda param in static initializer
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1843.v2.yml
Labels: autorelease, merge when ready

#1846 Implement automatic fixes for `ImmutablesStyle`
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyle.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutablesStyleTest.java
  changelog/@unreleased/pr-1846.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1850 Suppress existing `ProxyNonConstantType` failures to ease rollout
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ProxyNonConstantType.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ProxyNonConstantTypeTest.java
  changelog/@unreleased/pr-1850.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1851 Fix PreferSafeLogger edge case that produced non-compiling code
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLogger.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferSafeLoggerTest.java
  changelog/@unreleased/pr-1851.v2.yml
Labels: autorelease, merge when ready

#1853 StrictUnusedVariable exception for SafeLogger
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchBlockLogException.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CatchBlockLogExceptionTest.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-1853.v2.yml
Labels: autorelease, merge when ready
