Repository palantir/gradle-baseline, pull requests merged in 2021-01, with the labels that each got.

#1598 Implement error-prone ClassInitializationDeadlock check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ClassInitializationDeadlock.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ClassInitializationDeadlockTest.java
  changelog/@unreleased/pr-1598.v2.yml
Labels: autorelease, merge when ready

#1600 Add baseline-encoding plugin to force UTF-8 during compilation
  README.md
  changelog/@unreleased/pr-1600.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineEncoding.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-encoding.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineEncodingIntegrationTest.groovy
Labels: autorelease, merge when ready

#1603 Disable WhitespaceAround when using palantir-java-format
  changelog/@unreleased/pr-1603.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineConfigIntegrationTest.groovy
Labels: autorelease, merge when ready

#1606 Preserve DOCTYPE in checkstyle.xml
  changelog/@unreleased/pr-1606.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineConfig.java
Labels: autorelease, merge when ready

#1621 Automatically fix the new `ZoneIdOfZ` check
  changelog/@unreleased/pr-1621.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1593 Don't modify exact dependencies index
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
Labels: autorelease, merge when ready, no changelog

#1630 Fix error message to reflect correct static constant
  changelog/@unreleased/pr-1630.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready
