Repository palantir/gradle-baseline, pull requests merged in 2021-05, with the labels that each got.

#1750 Add baseline-immutables plugin to enable incremental compilation for Immutables
  README.md
  changelog/@unreleased/pr-1750.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineImmutables.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-immutables.properties
Labels: autorelease, merge when ready

#1752 Remove afterEvaluate from baseline immutables
  changelog/@unreleased/pr-1752.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineImmutables.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineImmutablesTest.groovy
Labels: autorelease, merge when ready

#1755 Don't use lambda to provider compiler arguments
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineImmutables.java
Labels: autorelease, merge when ready, no changelog

#1757 Ensure that Gradle CommandLineArgumentProvider are not written as lambdas
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/GradleCacheableArgumentProvider.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/GradleCacheableArgumentProviderTest.java
  changelog/@unreleased/pr-1757.v2.yml
Labels: autorelease, merge when ready

#1766 Replace our `BracesRequired` check+fix with upstream `MissingBraces`
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/BracesRequired.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/BracesRequiredTest.java
  changelog/@unreleased/pr-1766.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1764 Feature: Allow other plugins to register tasks to produce junit reports
  changelog/@unreleased/pr-1764.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCircleCi.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCircleCiJavaIntegrationTests.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineIntegrationTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/JunitReportsPluginSpec.groovy
  gradle-junit-reports/build.gradle
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/BuildFailureListener.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/CheckstyleReportHandler.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/DefaultTaskTimer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/Failure.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/FailuresSupplier.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JavacFailuresSupplier.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsExtension.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsFinalizer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsPlugin.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsRootPlugin.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitTaskResultExtension.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/StyleTaskTimer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/TaskTimer.java
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/Tasks.java
  gradle-junit-reports/src/test/groovy/com/palantir/gradle/junit/JunitReportsPluginIntegrationSpec.groovy
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/BuildFailureListenerTests.java
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/FailuresReportGeneratorTests.java
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/JavacFailuresSupplierTest.java
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/JunitReportsFinalizerTests.java
  gradle-junit-reports/src/test/java/com/palantir/gradle/junit/TestCommon.java
  versions.lock
Labels: merge when ready

#1773 Feature/avoid hashmapint
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AvoidNewHashMapInt.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/AvoidNewHashMapIntTest.java
  changelog/@unreleased/pr-1773.v2.yml
  docs/best-practices/java-coding-guidelines/readme.md
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: autorelease, merge when ready

#1775 Disable InlineMeSuggester by default
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: autorelease, merge when ready, no changelog
