Repository palantir/gradle-baseline, pull requests merged in 2021-11, with the labels that each got.

#1950 Feature: Zero Warmup Guava RateLimiter
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/NoWarmupRateLimiter.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/NoWarmupRateLimiterTest.java
  changelog/@unreleased/pr-1950.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease

#1944 Plumb Add-Exports through to execution and annotation processing sites
  changelog/@unreleased/pr-1944.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineModuleJvmArgsExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineModuleJvmArgs.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-module-jvm-args.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineModuleJvmArgsIntegrationTest.groovy
Labels: merge when ready, autorelease

#1954 Module export discovery handles jars with no manifest gracefully
  changelog/@unreleased/pr-1954.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineModuleJvmArgs.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineModuleJvmArgsIntegrationTest.groovy
Labels: merge when ready, autorelease

#1956 Support `--add-opens` in addition to `--add-exports`
  changelog/@unreleased/pr-1956.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineModuleJvmArgsExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineModuleJvmArgs.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineModuleJvmArgsIntegrationTest.groovy
Labels: merge when ready, autorelease

#1957 Revert "Feature: Zero Warmup Guava RateLimiter (#1950)"
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/NoWarmupRateLimiter.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/NoWarmupRateLimiterTest.java
  changelog/@unreleased/pr-1957.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease

#1958 Replace out instances of `RateLimiter.create(rate, Duration.ZERO)`
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ZeroWarmupRateLimiter.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ZeroWarmupRateLimiterTest.java
  changelog/@unreleased/pr-1958.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease

#1960 Improve Zero Warmup Rate Limiter to Catch Int Literals
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ZeroWarmupRateLimiter.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ZeroWarmupRateLimiterTest.java
  changelog/@unreleased/pr-1960.v2.yml
Labels: merge when ready, autorelease

#1965 versions plugin requires gradle 7
  changelog/@unreleased/pr-1965.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineJavaVersions.java
Labels: merge when ready, autorelease

#1966 Add error-prone check to prefer hasNoArgs
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AssertNoArgs.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/AssertNoArgsTest.java
  changelog/@unreleased/pr-1966.v2.yml
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#1967 Automatically fix AssertNoArgs
  changelog/@unreleased/pr-1967.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease

#1971 Add baseline-java-versions readme section
  README.md
Labels: merge when ready, no changelog

#1972 Add shaded junit5 deps as excluded name
  changelog/@unreleased/pr-1972.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy
Labels: merge when ready, autorelease

#1974 Fix errors setting test framework due to finalized property
  changelog/@unreleased/pr-1974.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/GradleTestVersions.java
Labels: merge when ready, autorelease

#1985 Remove BaselineErrorProneScope helper
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/BaselineErrorProneScope.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ClassInitializationDeadlock.java
Labels: merge when ready, no changelog

#1986 BaselineJavaVersions handles the lazy 'nebula.maven-publish' plugin
  changelog/@unreleased/pr-1986.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineJavaVersions.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaVersionIntegrationTest.groovy
Labels: merge when ready, autorelease

#1992 baseline-error-prone supports java8
  baseline-error-prone/build.gradle
  build.gradle
  changelog/@unreleased/pr-1992.v2.yml
Labels: merge when ready, autorelease

#1994 Downgrade spotless-plugin-gradle
  gradle/wrapper/gradle-wrapper.properties
  versions.lock
  versions.props
Labels: merge when ready, autorelease, no changelog

#1997 Revert "Downgrade spotless-plugin-gradle"
  gradle/wrapper/gradle-wrapper.properties
  versions.lock
  versions.props
Labels: merge when ready, autorelease, no changelog
