Repository palantir/gradle-baseline, pull requests merged in 2022-02, with the labels that each got.

#2061 improvement: Remove java 8 errorprone support
  changelog/@unreleased/pr-2061.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready

#2070 Ignore default methods in StrictUnusedVariable
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-2070.v2.yml
Labels: merge when ready, autorelease

#2076 enable annotation processing in eclipse by default
  build.gradle
  changelog/@unreleased/pr-2076.v2.yml
  gradle-baseline-java/baseline-class-uniqueness.lock
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineEclipse.groovy
  versions.lock
  versions.props
Labels: merge when ready

#2089 Use compileOnly configuration for immutables annotations
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesStyle.java
Labels: autorelease, no changelog
