Repository palantir/gradle-baseline, pull requests merged in 2022-08, with the labels that each got.

#2343 Add DefaultLocale check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DefaultLocale.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DefaultLocaleTest.java
  changelog/@unreleased/pr-2343.v2.yml
Labels: merge when ready, autorelease

#2351 Set the java launcher for Checkstyle tasks, too
  changelog/@unreleased/pr-2351.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
Labels: merge when ready, autorelease

#2348 Update error-prone configuration for gradle 7 up-to-date correctness
  README.md
Labels: merge when ready, no changelog

#2352 Error-prone 2.15.0
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#2355 Don't apply JUnit reports plugin by default
  changelog/@unreleased/pr-2355.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineCircleCi.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCircleCiJavaIntegrationTests.java
  gradle-junit-reports/src/main/resources/META-INF/gradle-plugins/com.palantir.junit-reports.properties
Labels: merge when ready, autorelease

#2357 Disable CanIgnoreReturnValueSuggester
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, autorelease, no changelog

#2360 Fix BaselineJavaVersion checkstyle configuration on gradle < 7.5
  changelog/@unreleased/pr-2360.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
Labels: merge when ready, autorelease

#2364 Apply more task config laziness to gradle-junit-reports
  changelog/@unreleased/pr-2364.v2.yml
  gradle-junit-reports/src/main/java/com/palantir/gradle/junit/JunitReportsPlugin.java
Labels: merge when ready, autorelease

#2363 Make baseline-exact-dependencies compatible with configure-on-demand
  changelog/@unreleased/pr-2363.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
Labels: merge when ready, autorelease

#2358 Update baseline-circleci README and tests
  README.md
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCircleCiIntegrationTest.groovy
Labels: merge when ready, no changelog

#2366 Add an errorprone check and typed annotation for Javax -> Jakarta
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ForbidJavaxParameterType.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SymbolPredicates.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ForbidJavaxParameterTypeTest.java
  changelog/@unreleased/pr-2366.v2.yml
  versions.lock
  versions.props
Labels: merge when ready, autorelease
