Repository palantir/gradle-baseline, pull requests merged in 2022-01, with the labels that each got.

#2024 Add FilterOutputStreamSlowMultibyteWrite
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWrite.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWriteTest.java
  changelog/@unreleased/pr-2024.v2.yml
Labels: merge when ready, autorelease

#2026 FilterOutputStreamSlowMultibyteWrite warns
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWrite.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWriteTest.java
  changelog/@unreleased/pr-2026.v2.yml
Labels: error-prone, merge when ready, autorelease

#2028 Add BugCheckerAutoService
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/BugCheckerAutoService.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/BugCheckerAutoServiceTest.java
  changelog/@unreleased/pr-2028.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: error-prone, merge when ready, autorelease

#2021 Suggest putting jupiter on runtime only
  changelog/@unreleased/pr-2021.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
Labels: merge when ready

#2031 Refine FilterOutputStreamSlowMultibyteWrite findings
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWrite.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/FilterOutputStreamSlowMultibyteWriteTest.java
  changelog/@unreleased/pr-2031.v2.yml
Labels: merge when ready, autorelease

#2032 Ban AfterburnerModule to reduce JDK-17 risk
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/AfterburnerJavaIncompatibility.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/AfterburnerJavaIncompatibilityTest.java
  changelog/@unreleased/pr-2032.v2.yml
  versions.lock
Labels: merge when ready, autorelease

#2036 Allow class types in DangerousIdentityKey
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousIdentityKey.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/DangerousIdentityKeyTest.java
  changelog/@unreleased/pr-2036.v2.yml
Labels: merge when ready, autorelease

#2038 Ignore junit-jupiter even when test deps not resolved
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineTesting.java
Labels: merge when ready, autorelease, no changelog

#2056 Prefer project modules on dependency resolution per default
  README.md
  changelog/@unreleased/pr-2056.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/Baseline.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselinePreferProjectModules.java
Labels: merge when ready, autorelease

#2052 Make compileRefaster task creation lazy
  changelog/@unreleased/pr-2052.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, autorelease

#2042 Add property to explicitly enable Error Prone
  changelog/@unreleased/pr-2042.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: merge when ready, autorelease
