Repository palantir/gradle-baseline, pull requests merged in 2022-09, with the labels that each got.

#2368 Workaround to IDEA-301084
  changelog/@unreleased/pr-2368.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
Labels: merge when ready, autorelease

#2369 Revert #2368 (Workaround to IDEA-301084)
  changelog/@unreleased/pr-2369.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
Labels: merge when ready, autorelease

#2376 java versions preview enhancements
  changelog/@unreleased/pr-2376.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersionExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersions.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersionsExtension.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersionsExtensionSetters.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/SubprojectBaselineJavaVersionsExtension.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaVersionIntegrationTest.groovy
Labels: autorelease

#2379 Fix bug
  changelog/@unreleased/pr-2379.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersionsExtension.java
Labels: merge when ready, autorelease

#2383 Enable switchBlockAsSingleDecisionPoint
  changelog/@unreleased/pr-2383.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready, autorelease

#2382 Implement a simple nullaway wrapper plugin
  baseline-null-away/README.md
  baseline-null-away/baseline-class-uniqueness.lock
  baseline-null-away/build.gradle
  changelog/@unreleased/pr-2382.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-null-away.properties
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineNullAwayIntegrationTest.groovy
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2386 Revert "Enable switchBlockAsSingleDecisionPoint (#2383)"
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready, autorelease, no changelog

#2387 Enable switchBlockAsSingleDecisionPoint
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineCheckstyleIntegrationTest.groovy
Labels: merge when ready, autorelease, no changelog

#2389 Roll back nullaway+checkerframework for jdk15 support
  changelog/@unreleased/pr-2389.v2.yml
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineNullAwayIntegrationTest.groovy
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2390 Exclude Spark UnusedStubClass from class uniqueness
  changelog/@unreleased/pr-2390.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/services/JarClassHasher.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
Labels: merge when ready, autorelease

#2393 lazily configure NullAway dependencies
  changelog/@unreleased/pr-2393.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineNullAwayIntegrationTest.groovy
Labels: merge when ready, autorelease

#2396 Don't opt in to CheckOptionalEmptiness
  changelog/@unreleased/pr-2396.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
Labels: merge when ready, autorelease

#2397 Disable NullAway for Test Source
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, autorelease, no changelog

#2402 Nullaway is not enabled in test sources
  changelog/@unreleased/pr-2402.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineNullAwayIntegrationTest.groovy
Labels: merge when ready, autorelease

#2400 Allow projects which don't use jdk-15 to resolve latest nullaway
  changelog/@unreleased/pr-2400.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
  versions.props
Labels: merge when ready, autorelease

#2403 Fix GitHub issues navigation Idea config
  changelog/@unreleased/pr-2403.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/util/GitUtils.java
Labels: merge when ready, autorelease

#2404 Verify nullaway doesn't apply to integration tests
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineNullAwayIntegrationTest.groovy
Labels: merge when ready, no changelog

#2405 Error-prone is enabled in idea for uniformity with CLI compilation
  changelog/@unreleased/pr-2405.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneIntegrationTest.groovy
Labels: merge when ready, autorelease

#2406 baseline-immutables adds required exports to the java compiler
  changelog/@unreleased/pr-2406.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineImmutables.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/plugins/BaselineImmutablesTest.groovy
Labels: merge when ready, autorelease

#2407 Refaster compilation uses exports matching error-prone compilation
  changelog/@unreleased/pr-2407.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CompileRefasterTask.java
Labels: merge when ready, autorelease

#2416 Implement ImmutableMapDuplicateKeyStrategy for obvious map construction
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutableMapDuplicateKeyStrategy.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ImmutableMapDuplicateKeyStrategyTest.java
  changelog/@unreleased/pr-2416.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease
