Repository palantir/gradle-baseline, pull requests merged in 2022-10, with the labels that each got.

#2414 Exclude javadoc @link from linelength
  changelog/@unreleased/pr-2414.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready, autorelease

#2422 Upgrade dependencies
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#2423 Use junit-vintage for JUnit 4 and Spock tests
  baseline-refaster-rules/build.gradle
  baseline-refaster-testing/build.gradle
  build.gradle
  versions.lock
  versions.props
Labels: merge when ready

#2417 Update a couple toLowerCase calls with Locale.ROOT
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ImmutablesBuilderMissingInitialization.java
Labels: merge when ready, no changelog

#2427 Fix ConcurrentModificationExceptions thrown from BaselineNullAway
  changelog/@unreleased/pr-2427.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineNullAway.java
Labels: merge when ready, autorelease

#2433 Revert dependency bump which prevented some tests from running
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JooqResultStreamLeakTest.java
  baseline-refaster-rules/build.gradle
  baseline-refaster-testing/build.gradle
  build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#2441 upgrade nullaway
  versions.lock
  versions.props
Labels: merge when ready, autorelease, no changelog
