Repository palantir/gradle-baseline, pull requests merged in 2023-03, with the labels that each got.

#2472 Upgrade error_prone to 2.18.0 (from 2.16)
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LogsafeArgName.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/safety/SafetyPropagationTransfer.java
  build.gradle
  changelog/@unreleased/pr-2472.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#2505 Prefer Guava version of VisibleForTesting annotation
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferCommonAnnotations.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferCommonAnnotationsTest.java
  changelog/@unreleased/pr-2505.v2.yml
Labels: merge when ready

#2510 Fix comment from previous PR
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousCollapseKeysUsage.java
Labels: merge when ready, no changelog

#2506 add JooqBatchWithoutBindArgs check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/JooqBatchWithoutBindArgs.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/JooqBatchWithoutBindArgsTest.java
  changelog/@unreleased/pr-2506.v2.yml
Labels: merge when ready, autorelease

#2521 Remove support for refaster
  .baseline/checkstyle/custom-suppressions.xml
  README.md
  baseline-refaster-javac-plugin/build.gradle
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompiler.java
  baseline-refaster-javac-plugin/src/main/java/com/palantir/baseline/refaster/BaselineRefasterCompilerAnalyzer.java
  baseline-refaster-rules/build.gradle
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/AddAllArrayToBuilder.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/CollectionsIsEmpty.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/InvocationTargetExceptionCause.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/OptionalOrElseSupplier.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SortedFirst.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/SortedFirstNatural.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/TritiumReplaceGauge.java
  baseline-refaster-rules/src/main/java/com/palantir/baseline/refaster/Utf8Length.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/AddAllArrayToBuilderTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/CollectionsIsEmptyTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/InvocationTargetExceptionCauseTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/OptionalOrElseSupplierTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SortedFirstNaturalTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/SortedFirstTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/TritiumReplaceGaugeTest.java
  baseline-refaster-rules/src/test/java/com/palantir/baseline/refaster/Utf8LengthTest.java
  baseline-refaster-testing/build.gradle
  baseline-refaster-testing/src/main/java/com/palantir/baseline/refaster/CompilerUtility.java
  baseline-refaster-testing/src/main/java/com/palantir/baseline/refaster/RefasterTestHelper.java
  changelog/@unreleased/pr-2521.v2.yml
  gradle-baseline-java/build.gradle
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CompileRefasterTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineErrorProneRefasterIntegrationTest.groovy
  settings.gradle
  versions.lock
Labels: merge when ready

#2535 SafeLoggingPropagation uses new ASTHelpers.isRecord function
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SafeLoggingPropagation.java
Labels: merge when ready, no changelog

#2537 StrictUnusedVariable is not suppressed when UnusedVariable is disabled
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StrictUnusedVariableTest.java
  changelog/@unreleased/pr-2537.v2.yml
Labels: merge when ready, autorelease

#2530 Add check: Use Collection.isEmpty() instead of comparing size() with 0
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CardinalityEqualsZero.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/CardinalityEqualsZeroTest.java
  changelog/@unreleased/pr-2530.v2.yml
Labels: merge when ready, autorelease
