Repository palantir/gradle-baseline, pull requests merged in 2024-03, with the labels that each got.

#2745 Promote BaselineJavaVersionExtension.library in README
  README.md
Labels: merge when ready, no changelog

#2743 Re-enable GradleProviderToString
  build.gradle
Labels: merge when ready, no changelog

#2749 Check runtime classpath contains compatible jars
  changelog/@unreleased/pr-2749.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/CheckClasspathCompatible.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/ChosenJavaVersion.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaVersionIntegrationTest.groovy
Labels: merge when ready, autorelease

#2746 Suppress more checks in Gradle plugin projects
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, autorelease, no changelog

#2752 Handle relocated multi-release class files in checkRuntimeClasspathCompatible
  changelog/@unreleased/pr-2752.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/CheckClasspathCompatible.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaVersionIntegrationTest.groovy
Labels: merge when ready, autorelease

#2748 Ignore intra-project dependencies in checkUnusedDependencies
  changelog/@unreleased/pr-2748.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready, autorelease

#2768 Lazily provide self coordinate to checkUnusedDependencies
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineExactDependencies.java
Labels: merge when ready, autorelease, no changelog
