Repository palantir/gradle-baseline, pull requests merged in 2024-05, with the labels that each got.

#2781 Add fix parameter to checkClassUniqueness
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineClassUniquenessPlugin.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
  gradle-baseline-java/src/test/resources/com/palantir/baseline/baseline-class-uniqueness.expected.lock
Labels: merge when ready, autorelease, no changelog

#2791 Reduce memory usage of `checkClasspathCompatible`
  changelog/@unreleased/pr-2791.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/CheckClasspathCompatible.java
Labels: merge when ready, autorelease

#2783 Gradle JDK automanagement integration for toolchains
  .gitignore
  changelog/@unreleased/pr-2783.v2.yml
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersion.java
  gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/javaversions/BaselineJavaVersionsExtension.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineJavaVersionIntegrationTest.groovy
Labels: merge when ready, autorelease

#2804 Adding TestFactory as a method that ignores DesignForExntesion along other test methods
  .baseline/checkstyle/checkstyle.xml
  changelog/@unreleased/pr-2804.v2.yml
Labels: merge when ready

#2806 Remove ClassInitializationDeadlock
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ClassInitializationDeadlock.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/ClassInitializationDeadlockTest.java
Labels: merge when ready, autorelease, no changelog

#2808 Upgrade Error Prone
  baseline-error-prone/build.gradle
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/CatchSpecificity.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/FinalClass.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/OptionalOrElseThrowThrows.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease, no changelog
