Repository palantir/gradle-baseline, pull requests merged in 2025-04, with the labels that each got.

#3083 Delete unused images/checkstyle-circle-failure.png
  images/checkstyle-circle-failure.png
Labels: merge when ready, no changelog

#3090 Fix gradle 7 compat for checkClassUniquenessTask
  changelog/@unreleased/pr-3090.v2.yml
  gradle-baseline-java/src/main/java/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineClassUniquenessPluginIntegrationTest.groovy
Labels: merge when ready, autorelease

#3093 Replace getAllModuleArtifacts with getModuleArtifacts
  gradle-baseline-java/src/main/java/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/java/com/palantir/baseline/tasks/CheckImplicitDependenciesTask.java
  gradle-baseline-java/src/main/java/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/AbstractPluginTest.groovy
  gradle-baseline-java/src/test/groovy/com/palantir/baseline/BaselineExactDependenciesTest.groovy
Labels: merge when ready, autorelease, no changelog

#3095 Revert "Restore error message"
  gradle-baseline-java/src/main/java/com/palantir/baseline/plugins/BaselineExactDependencies.java
  gradle-baseline-java/src/main/java/com/palantir/baseline/tasks/CheckUnusedDependenciesTask.java
Labels: merge when ready, no changelog

#3096 Convert flatMap(Streams::stream) to Stream.mapMulti(Optional::isPresent)
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StreamFlatMapOptional.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StreamFlatmapOptionalTest.java
  changelog/@unreleased/pr-3096.v2.yml
Labels: merge when ready, autorelease
