Repository palantir/gradle-baseline, pull requests merged in 2025-01, with the labels that each got.

#2966 baseline-error-prone targets jdk-17+
  baseline-error-prone/build.gradle
  changelog/@unreleased/pr-2966.v2.yml
Labels: merge when ready, autorelease

#2983 Fix missing space in error message
  gradle-baseline-java/src/main/java/com/palantir/baseline/tasks/CheckClassUniquenessLockTask.java
Labels: merge when ready, no changelog

#2986 baseline-error-prone takes advantage of jdk17 compiler APIs
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/DangerousRecordArrayField.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MoreASTHelpers.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Records.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/SafeLoggingPropagation.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/safety/SafetyAnnotations.java
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/safety/SafetyPropagationTransfer.java
Labels: merge when ready, autorelease, no changelog

#2988 safe-logging analysis correctly handles out-of-scope parameter references
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/safety/SafetyPropagationTransfer.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/IllegalSafeLoggingArgumentTest.java
  changelog/@unreleased/pr-2988.v2.yml
Labels: merge when ready, autorelease, no changelog

#2998 Dramatically simplify the UnnecessarilyQualified check
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/UnnecessarilyQualified.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/UnnecessarilyQualifiedTest.java
  changelog/@unreleased/pr-2998.v2.yml
Labels: merge when ready, autorelease

#2999 Disable expensive LambdaMethodReference by default
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LambdaMethodReference.java
  changelog/@unreleased/pr-2999.v2.yml
  gradle-baseline-java/src/main/java/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
  gradle-baseline-java/src/main/java/com/palantir/baseline/plugins/BaselineErrorProne.java
Labels: merge when ready, autorelease

#3024 Fix StreamFlatMapOptional wildcard types
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StreamFlatMapOptional.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/StreamFlatmapOptionalTest.java
  changelog/@unreleased/pr-3024.v2.yml
Labels: error-prone, merge when ready, autorelease
