Repository palantir/gradle-baseline, pull requests merged in 2025-07, with the labels that each got.

#3147 [Safe-logging] Get safety from type parameter arguments
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/safety/SafetyAnnotations.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/IllegalSafeLoggingArgumentTest.java
  changelog/@unreleased/pr-3147.v2.yml
Labels: merge when ready, autorelease

#3173 Add PreferUncheckedIoException check
  README.md
  baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferUncheckedIoException.java
  baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferUncheckedIoExceptionTest.java
  changelog/@unreleased/pr-3173.v2.yml
Labels: merge when ready, autorelease

#3175 Add PreferUncheckedIoException to default patch checks
  gradle-baseline-java/src/main/java/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease, no changelog

#3179 update individual plugins readme
  README.md
  gradle-baseline-java/src/main/resources/META-INF/gradle-plugins/com.palantir.baseline-java-compiler-heap.properties
Labels: merge when ready, no changelog

#3184 Patch StatementSwitchToExpressionSwitch by default
  gradle-baseline-java/src/main/java/com/palantir/baseline/extensions/BaselineErrorProneExtension.java
Labels: merge when ready, autorelease, no changelog

#3182 Add a message for the IllegalType checkstyle check
  changelog/@unreleased/pr-3182.v2.yml
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready, autorelease

#3196 Remove Preconditions RegexpSinglelineJava checkstyle rule
  gradle-baseline-java-config/resources/checkstyle/checkstyle.xml
Labels: merge when ready, autorelease, no changelog
